import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useAuth } from "../context/AuthContext";

export default function Logout() {
  const { loading, logout } = useAuth();

  const handleLogout = async (e) => {
    e.preventDefault();
    await logout();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {loading ? (
          <p>Loading</p>
        ) : (
          <>
            <button
              onClick={(e) => {
                handleLogout(e);
              }}
              type="submit"
            >
              Logout
            </button>
          </>
        )}
      </main>

      <footer className={styles.footer}>
        <p>This is the footer</p>
      </footer>
    </div>
  );
}
